import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/MontserratAlternates-Medium.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});



export const metadata = {
  title: "Suriya Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable}  `}
      >
        {children}
      </body>
    </html>
  );
}
